spring.application.name=rental-eventos

# Banco de dados
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5433/postgres
spring.datasource.username=postgres
spring.datasource.password=aluno

spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true
spring.jpa.show-sql=true
spring.datasource.driver-class-name=org.postgresql.Driver

# Swagger
springdoc.swagger-ui.path=/rental-eventos/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true

# JWT
jwt.secret=rental-eventos-chave-secreta-2026-seguranca
jwt.expiration=86400000