#services:
#  - type: web
#    name:  hospital_com_vida #Estava como "projeto-integrador" no tópico 4 da prova do módulo 2. Não entendi.
#    env: docker
#    plan: free
#    autoDeploy: true
#    region: oregon
#    dockerfilePath: ./dockerfilePath
#    envVars:
#      - key: SPRING_PROFILES_ACTIVE
#        value: prod
#      - key: JAVA_OPTS
#        value: "-Xms256m -Xmx512m"
#      - key: PORT
#        value: 8080